export const items1 = [
	{
		title: "峰会直播",
		description: "2021",
		icon: "/src/assets/1-icon.png",
		routerName: "",
		iconTop: "2.1rem",
		iconLeft: "2.7rem",
		titleTop: "0.4rem",
		titleLeft: "0.4rem",
		jumpBtnTop: "0.0rem",
		jumpBtnLeft: "2.7rem",
		background: "linear-gradient(-55deg, #1D2089, #C51523)",
		width: "3.4rem",
		height: "3.4rem",
	},
];

export const items2 = [
	{
		title: "大会简介",
		description: "",
		icon: "/src/assets/2-icon.png",
		iconTop: "",
		iconLeft: "",
		titleTop: "",
		titleLeft: "",
		jumpBtnTop: "",
		jumpBtnLeft: "",
		background: "#232FD0",
		width: "3.48rem",
		height: "0.97rem",
		routerName: "MeetingIntroduction",
	},
	{
		title: "峰会日程",
		description: "",
		icon: "/src/assets/3-icon.png",
		iconTop: "",
		iconLeft: "",
		titleTop: "",
		titleLeft: "",
		jumpBtnTop: "",
		jumpBtnLeft: "",
		background: "#232FD0",
		width: "3.48rem",
		height: "0.97rem",
		routerName: "MeetingSchedule",
	},
	{
		title: "嘉宾简介",
		description: "",
		icon: "/src/assets/4-icon.png",
		iconTop: "",
		iconLeft: "",
		titleTop: "",
		titleLeft: "",
		jumpBtnTop: "",
		jumpBtnLeft: "",
		background: "#232FD0",
		width: "3.48rem",
		height: "0.97rem",
		routerName: "GuestIntroduction",
	},
];
export const items3 = [
	{
		title: "文件下载",
		description: "",
		icon: "/src/assets/5-icon.png",
		iconTop: "0.6rem",
		iconLeft: "2.4rem",
		titleTop: "0.4rem",
		titleLeft: "0.4rem",
		jumpBtnTop: "0.6rem",
		jumpBtnLeft: "0.4rem",
		background: "#232FD0",
		width: "3.4rem",
		height: "1.8rem",
		routerName: "DownloadList",
	},
];
export const items4 = [
	{
		title: "我要报名",
		routerName: "AppForm",
		description: "",
		icon: "/src/assets/6-icon.png",
		iconTop: "0.6rem",
		iconLeft: "2.4rem",
		titleTop: "0.4rem",
		titleLeft: "0.4rem",
		jumpBtnTop: "0.6rem",
		jumpBtnLeft: "0.4rem",
		background: "#232FD0",
		width: "3.4rem",
		height: "1.8rem",
	},
];
export const items5 = [
	{
		title: "交通安排",
		description: "",
		icon: "/src/assets/7-icon.png",
		iconTop: "-0.1rem",
		iconLeft: "0.8rem",
		titleTop: "1.2rem",
		titleLeft: "0.4rem",
		jumpBtnTop: "1.3rem",
		jumpBtnLeft: "",
		background: "#232FD0",
		width: "2.22rem",
		height: "2.5rem",
		routerName: "TrafficPlan",
	},
];
export const items6 = [
	{
		title: "会场指引",
		description: "",
		icon: "/src/assets/8-icon.png",
		iconTop: "-0.1rem",
		iconLeft: "0.8rem",
		titleTop: "1.2rem",
		titleLeft: "0.4rem",
		jumpBtnTop: "1.3rem",
		jumpBtnLeft: "",
		background: "#232FD0",
		width: "2.22rem",
		height: "2.5rem",
		routerName: "MeetingGuide",
	},
];
export const items7 = [
	{
		title: "联系我们",
		description: "",
		icon: "/src/assets/9-icon.png",
		iconTop: "-0.1rem",
		iconLeft: "0.8rem",
		titleTop: "1.2rem",
		titleLeft: "0.4rem",
		jumpBtnTop: "1.3rem",
		jumpBtnLeft: "",
		background: "#232FD0",
		width: "2.22rem",
		height: "2.5rem",
		routerName: "ContactUs",
	},
];